import type { Metadata } from "next";
import { Basic } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const basic = Basic({
  variable: "--font-basic",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Friends Of Like Minds",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${basic.className} antialiased min-h-screen flex flex-col`}>
        <Navbar />
        <main className="flex-1 flex flex-col bg-[#FBF9ED]">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
